### ISSUE TITLE
交换友链

### ISSUE THREAD

**Issue by baipin** [Cyanoxygen/cyanrepo#2]
交换友链，实在联系不上你，发了邮件一直没有回音...
麻烦检查一下电子邮箱，2月11日发的一直未见回复( •́ὤ•̀)

**Comment by Cyanoxygen** [comment]
很抱歉，我去看一下邮箱。

**Comment by Cyanoxygen** [comment]
It looks like yandex has filtered your email. You can send email to cyanoxygen2725@gmail.com directly. Sorry!

**Comment by Cyanoxygen** [comment]
And next time please file issues to cyanoxygen/cyanoxygen.github.io . This issue will be deleted after closed.
